---
# file: group_vars/all
# ansible_ssh_user: leggers

# webapp
deploy_directory: /var/www
app_names: [shop, artemix]

# ruby
ruby: 2.1.1
rubyTmpDir: /usr/local/src
rubyUrl: http://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.1.tar.gz
rubyCompressedFile: ruby-2.1.1.tar.gz
rubyName: ruby-2.1.1
tmpRubyPath: "{{rubyTmpDir}}/{{rubyName}}"

# passenger
passenger_version: 4.0.40

# db
db_user: username
db_password: password # need to set this with obfuscated script call