---
# File: shop-data-sync.yml
# Purpose: copies store production data to staging and dev servers (as per boss's request)

- hosts: production
  tasks:
    - name: sqldump production database
      mysql_db: name=bomb_shop_production state=dump target=/home/deploy/sql_dumps/prod_dump_{{ansible_date_time.date}}.sql
      sudo: yes

    - name: sync db dump to local
      synchronize: mode=pull dest=~/work/bombsheller/sql_dumps/prod_dump_{{ansible_date_time.date}}.sql src=/home/deploy/sql_dumps/prod_dump_{{ansible_date_time.date}}.sql
      sudo: yes

    - name: sync product images to local
      synchronize: mode=pull dest=~/work/bombsheller/bomb_store/public src=/var/www/shop/shared/public/spree delete=yes

- hosts: non-production
  vars_files:
    - group_vars/use-deploy-ssh-user.yml
  tasks:
    - name: copy database dump to remote
      copy: src=~/work/bombsheller/sql_dumps/prod_dump_{{ansible_date_time.date}}.sql dest=/home/deploy/sql_dumps/prod_dump_{{ansible_date_time.date}}.sql owner=deploy group=deploy

    - name: import data into remote database
      shell: mysql bomb_shop_{{rails_env}} < /home/deploy/sql_dumps/prod_dump_{{ansible_date_time.date}}.sql

    - name: sync production images to remote
      synchronize: mode=push src=~/work/bombsheller/bomb_store/public/spree dest=/var/www/shop/shared/public delete=yes
      remote_user: deploy

- hosts: non-production
  sudo: yes
  vars_files:
    - group_vars/use-leggers-ssh-user.yml
  tasks:
    - name: enable site
      file: state=link src=/etc/apache2/sites-available/shop.conf dest=/etc/apache2/sites-enabled/shop.conf
      register: link_created

    - name: restart apache if link created
      service: name=apache2 state=restarted
      when: link_created.changed

    - name: reload apache2 if link created
      service: name=apache2 state=reloaded
      when: link_created.changed