- hosts: all
  sudo: yes
  vars_files:
    - group_vars/all.yml
    - group_vars/secrets.yml

  roles:
    - common
    - webserver
    - db

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted

    - name: reload apache
      service: name=apache2 state=reloaded