---
# inspiration from https://www.digitalocean.com/community/articles/how-to-install-and-secure-phpmyadmin-on-ubuntu-14-04

- name: Install PHP and phpMyAdmin
  apt: pkg={{item}}
  with_items:
    - php5
    - libapache2-mod-php5
    - php5-mcrypt
    - phpmyadmin

- name: Link phpMyAdmin apache config file
  file: state=link src=/etc/phpmyadmin/apache.conf dest=/etc/apache2/conf-enabled/phpmyadmin.conf
  notify:
    - reload apache
    - restart apache