- name: ensure LANG_ALL is set in locale file
  sudo: yes
  lineinfile: dest=/etc/default/locale line='LANG_ALL="en_US.UTF-8"'
  notify:
    - regenerate locales

- name: ensure LANGUAGE is set in locale file
  sudo: yes
  lineinfile: dest=/etc/default/locale line='LANGUAGE="en_US.UTF-8"'
  notify:
    - regenerate locales

- name: ensure LANG is set in locale file
  sudo: yes
  lineinfile: dest=/etc/default/locale line='LANG="en_US.UTF-8"'
  notify:
    - regenerate locales

- name: ensure LC_ALL is set in locale file
  sudo: yes
  lineinfile: dest=/etc/default/locale line='LC_ALL="en_US.UTF-8"'
  notify:
    - regenerate locales