- name: Ensure apache packages are installed
  apt: pkg={{item}}
  with_items:
    - libcurl4-openssl-dev
    - libssl-dev
    - zlib1g-dev
    - apache2-mpm-prefork
    - apache2-prefork-dev
    - libapr1-dev
    - libaprutil1-dev

# inspiration: http://www.modrails.com/documentation/Users%20guide%20Apache.html#install_on_debian_ubuntu
- name: Add passenger keyserver
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x3D3B6BD098080A60 state=present

- name: Add HTTPS support for APT
  apt: pkg={{item}}
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Copy passenger.list
  copy: src=../files/passenger.list dest=/etc/apt/sources.list.d/passenger.list owner=root mode=600

- name: Ensure passenger apache package is installed
  apt: pkg=libapache2-mod-passenger force=yes

- name: Ensure apache app config files are present
  template: src=apache-config.j2 dest=/etc/apache2/sites-available/{{item}}.conf owner=deploy group=deploy
  with_items: app_names
  notify:
    - restart apache

- name: Ensure apache config files are symlinked
  file: src=/etc/apache2/sites-available/{{item}} dest=/etc/apache2/sites-enabled/{{item}}.conf
  with_items: app_names
  notify:
    - reload apache