---

- name: Upgrade apt
  apt: upgrade=yes update_cache=yes

- name: Install app dependencies
  apt: pkg={{item}}
  with_items:
    - nodejs
    - imagemagick

- name: Create deployment group
  group: name=deploy

- name: Create deployment user
  user: name=deploy group=deploy comment="Application deployment user" shell=/bin/bash

- name: add Lucas's key for deploy user
  authorized_key: user=deploy key="{{ lookup('file', '/Users/leggers/work/bombsheller/authorized-keys/lucas') }}"

- name: add Pablos's key for deploy user
  authorized_key: user=deploy key="{{ lookup('file', '/Users/leggers/work/bombsheller/authorized-keys/pablos') }}"

- name: Deploy user's bashrc
  template: dest=/home/deploy/.bashrc src=bashrc.j2 owner=deploy group=deploy

- name: Deploy user's bash_profile
  copy: dest=/home/deploy/.bash_profile src=bash_profile.txt owner=deploy group=deploy

- name: Create deployment directory
  file: path={{deploy_directory}}/{{item}} owner=deploy group=deploy state=directory
  with_items: app_names

- name: Make shared directories
  file: path={{deploy_directory}}/{{item[0]}}/shared/{{item[1]}} group=deploy owner=deploy state=directory
  with_nested:
    - app_names
    - [ tmp, log, public, bundle, bin, config ]

- name: Ensure database.yml is configured
  template: src=database.yml.j2 dest={{deploy_directory}}/{{item}}/shared/config/database.yml force=yes mode=755 owner=deploy group=deploy
  with_items: app_names

- name: make sql_dumps directory
  file: path=/home/deploy/sql_dumps state=directory owner=deploy group=deploy