---

- name: Upgrade apt
  apt: upgrade=yes update_cache=yes

- name: Install app dependencies 
  apt: pkg={{item}}
  with_items:
    - nodejs
    - imagemagick

- name: Create deployment group
  group: name=deploy

- name: Create deployment user
  user: name=deploy group=deploy comment="Application deployment user"

- authorized_key: user=deploy key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Deploy user's bashrc
  template: dest=/home/deploy/.bashrc src=bashrc.j2 owner=deploy group=deploy

- name: Deploy user's bash_profile
  copy: dest=/home/deploy/.bash_profile src=bash_profile.txt owner=deploy group=deploy

- name: Deploy user use bash
  shell: chsh -s {{ansible_env.SHELL}} deploy

- name: Create deployment directory
  file: path={{deploy_directory}}/{{item}} owner=deploy group=deploy state=directory
  with_items: app_names

- name: Make shared directories
  file: path={{deploy_directory}}/{{item[0]}}/shared/{{item[1]}} group=deploy owner=deploy state=directory
  with_nested:
    - app_names
    - [ tmp, log, public, bundle, bin, config ]
  tags: shared

- name: Install database.yml
  template: src=database.yml.j2 dest={{deploy_directory}}/{{item}}/shared/config/database.yml force=yes mode=755 owner=deploy group=deploy
  with_items: app_names