---
# Installs ruby from source

- name: Install ruby dependencies
  apt: pkg={{item}}
  with_items:
    - build-essential
    - automake
    - bison
    - autoconf
    - pkg-config
    - libreadline6
    - libreadline6-dev
    - openssl
    - libssl-dev
    - curl
    - git-core
    - zlib1g
    - zlib1g-dev
    - libyaml-dev
    - libsqlite3-dev
    - libxml2-dev
    - libxslt1-dev
    - libgdbm-dev
    - libncurses5-dev
    - libtool
    - libffi-dev
    - gawk
    - sqlite3

- name: install rvm
  shell: \curl -L https://get.rvm.io | bash -s stable creates=~/.rvm executable=/bin/bash
  remote_user: deploy
  sudo: no

- name: install ruby
  shell: ~/.rvm/bin/rvm install --default {{ruby}} creates=~/.rvm/rubies/ruby-{{ruby}} executable=/bin/bash
  remote_user: deploy
  sudo: no

- name: ensure bundle is installed
  shell: gem install bundle creates=~/.rvm/gems/ruby-{{ruby}}@global/bin/bundle executable=/bin/bash
  remote_user: deploy
  sudo: no